//AUTH
// ** Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ONLINE = 'ONLINE';
export const OFFLINE = 'OFFLINE';

// ** Register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
// ** Forgot Password
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAILURE = 'FORGOT_FAILURE';
// ** Reset Password
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';

// ** OnBoard
export const ON_BOARD_REQUEST = 'ON_BOARD_REQUEST';
export const ON_BOARD_SUCCESS = 'ON_BOARD_SUCCESS';
export const ON_BOARD_FAILURE = 'ON_BOARD_FAILURE';

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_FAILURE = "OTP_FAILURE";

export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";

export const HOME_REQUEST = "HOME_REQUEST";
export const HOME_SUCCESS = "HOME_SUCCESS";
export const HOME_FAILURE = "HOME_FAILURE";

export const MY_STANDING_REQUEST = "MY_STANDING_REQUEST";
export const MY_STANDING_SUCCESS = "MY_STANDING_SUCCESS";
export const MY_STANDING_FAILURE = "MY_STANDING_FAILURE";

export const MY_TEAM_DETAIL_REQUEST = "MY_TEAM_DETAIL_REQUEST";
export const MY_TEAM_DETAIL_SUCCESS = "MY_TEAM_DETAIL_SUCCESS";
export const MY_TEAM_DETAIL_FAILURE = "MY_TEAM_DETAIL_FAILURE";

export const LEADERBOARD_REQUEST = "LEADERBOARD_REQUEST";
export const LEADERBOARD_SUCCESS = "LEADERBOARD_SUCCESS";
export const LEADERBOARD_FAILURE = "LEADERBOARD_FAILURE";

export const UPDATE_HEALTH_REQUEST = "UPDATE_HEALTH_REQUEST";
export const UPDATE_HEALTH_SUCCESS = "UPDATE_HEALTH_SUCCESS";
export const UPDATE_HEALTH_FAILURE = "UPDATE_HEALTH_FAILURE";


export const GAME_DETAIL_REQUEST = "GAME_DETAIL_REQUEST";
export const GAME_DETAIL_SUCCESS = "GAME_DETAIL_SUCCESS";
export const GAME_DETAIL_FAILURE = "GAME_DETAIL_FAILURE";

export const GAMES_REQUEST = "GAMES_REQUEST";
export const GAMES_SUCCESS = "GAMES_SUCCESS";
export const GAMES_FAILURE = "GAMES_FAILURE";

export const CALENDER_INFO_REQUEST = "CALENDER_INFO_REQUEST";
export const CALENDER_INFO_SUCCESS = "CALENDER_INFO_SUCCESS";
export const CALENDER_INFO_FAILURE = "CALENDER_INFO_FAILURE";

export const CALENDER_INDICATOR_REQUEST = "CALENDER_INDICATOR_REQUEST";
export const CALENDER_INDICATOR_SUCCESS = "CALENDER_INDICATOR_SUCCESS";
export const CALENDER_INDICATOR_FAILURE = "CALENDER_INDICATOR_FAILURE";

// CHAT
export const CHAT_USER_LIST_REQUEST = "CHAT_USER_LIST_REQUEST";
export const CHAT_USER_LIST_SUCCESS = "CHAT_USER_LIST_SUCCESS";
export const CHAT_USER_LIST_FAILURE = "CHAT_USER_LIST_FAILURE";

export const CHAT_MESSAGE_REQUEST = "CHAT_MESSAGE_REQUEST";
export const CHAT_MESSAGE_SUCCESS = "CHAT_MESSAGE_SUCCESS";
export const CHAT_MESSAGE_FAILURE = "CHAT_MESSAGE_FAILURE";