export const Fonts = {
  Black: 'Metropolis-Black',
  BlackItalic: 'noah-bolditalic',
  // Bold: 'Metropolis-Bold',
  Bold: 'noah-bold',
  // BoldItalic: 'Metropolis-BoldItalic',
  BoldItalic: 'noah-bolditalic',
  XBold: 'noah-bold',
  XBoldItalic: 'noah-bolditalic',
  Xlight: 'noah-regular',
  XlightItalic: 'noah-regularitalic',
  Medium: 'noah-regular',
  MediumItalic: 'noah-regularitalic',
  // Regular: 'Metropolis-Regular',
  Regular: 'noah-regular',
  RegularItalic: 'noah-regularitalic',
  SemiBold: 'noah-bold',
  SemiBoldItalic: 'noah-bolditalic',
  Thin: 'noah-regular',
  ThinItalic: 'noah-regularitalic',
};
